### ISSUE TITLE
[FR] Ability to set Message Title

### ISSUE THREAD

**Issue by sergeifilippov** [fabianonline/telegram.sh#12]
It would be awesome to be able to set the message title which would give your notifications more context. Like this:

![Telegram 2020-05-06 12-35-25](https://user-images.githubusercontent.com/123676/81128709-0762c000-8f96-11ea-9b5e-4a0339faaeb6.png)

eg. https://github.com/NicolasBernaerts/debian-scripts/blob/master/telegram/telegram-notify

**Comment by fabianonline** [comment]
Added it. You can now supply a title with `-T`. Bold formatting is used only if you use `-H` for HTML or `-M` for Markdown mode as well.
