### ISSUE TITLE
make it installable

### ISSUE THREAD

**Issue by venil7** [fabianonline/telegram.sh#13]
Make this script installable via `curl` or `wget`

please look at how `rustup` and `nvm` (and many others) have done it:
 - rustup `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
 - nvm `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash`

**Comment by fabianonline** [comment]
Install scripts may be useful for big projects, but I don't see much need for install scripts for such a small tool as this. You could just do something like this to install it:

`sudo curl -o /usr/local/bin/telegram https://raw.githubusercontent.com/fabianonline/telegram.sh/master/telegram && sudo chmod +x /usr/local/bin/telegram`

**Comment by venil7** [comment]
Maybe worth mentioning this in a `readme`

**Comment by deadda7a** [comment]
It's not a good idea to curl | (sudo) bash anything.

**Comment by Bryce-Dixon** [comment]
I feel like anyone with enough experience to be looking for a bash-based Telegram CLI would know how the PATH works and therefore know that you just have to put programs (or links) in `/usr/local/bin` to "install" them.
