### ISSUE TITLE
Please create a tag/release - for use with Homebrew

### ISSUE THREAD

**Issue by Grynn** [fabianonline/telegram.sh#28]
Nothing fancy needed, just something like:

1. `git tag v0.0.4`
2. `git push --tags`
3. `gh release create --draft --title "$(shell git describe --tags)"`

Without a tag/release not sure if I (or any third-party) can make a Homebrew formula.

Homebrew makes installing so much easier!

**Comment by fabianonline** [comment]
Created release v0.5
