### ISSUE TITLE
Add disable_web_page_preview option

### ISSUE THREAD

**Issue by veez21** [fabianonline/telegram.sh#3]
Add an option for disabling webpage previous from links

`disable_web_page_preview=True`

**Comment by Dyneteve** [comment]
+200

**Comment by Dyneteve** [comment]
@fabianonline

**Comment by fabianonline** [comment]
Added in 5a5f360f4ac0f82dabac6e7dffda9e87461cd72e.

You can now use `-D` or alternatively set `TELEGRAM_DISABLE_WEB_PAGE_PREVIEW=true` in your config to have it enabled by default.

While I was at it, I also added `-N` and `TELEGRAM_DISABLE_NOTIFICATION=true` for when you want to get silent notifications on your smartphone.
