### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mikekgr** [fabianonline/telegram.sh#31]
Dear Developer, Dear Sirs,
first of all I would like to thank you for this extremely useful bash script, it is working fine !
My question / features request is to expand it in order to get also messages from telegram, is is possible?
I already searched the GitHub and I found telegram-cli but it's (or seems to ) abandoned.
Please consider this request or if it's impossible, introduce me any Linux (better Ubuntu 22.04 based) that can receive from telegram.
Thanks and Best Regards,
Mike Kranidis

**Comment by electr1fy0** [comment]
~/telegram -m

**Comment by mikekgr** [comment]
> ~/telegram -m

Thanks a lot !
