### ISSUE TITLE
How to send a file with spaces or/and brackets

### ISSUE THREAD

**Issue by w-b-kelso** [fabianonline/telegram.sh#9]
I've got a problem with sending a file which contains spaces and/or brackets.

I want to send `"/tmp/(2019) Test/test.jpg"` with `telegram.sh -i /tmp/(2019) Test/test.jpg`, but the answer is `-bash: syntax error near unexpected token `('`

If I try `telegram.sh /tmp/test 1.jpg` the answer is `The file /tmp/test does not exist.`

Is there a solution?

**Comment by foreverdante** [comment]
Use single quotes (' '). This will cause the shell to use a string-literal and will treat spaces and some special characters as literals. So `telegram.sh /tmp/test 1.jpg` will be read all the way up to the first space in the first position. Then there is the space and it's telling the shell that there is a second position. 

Another way to get around the space and special character issue is to escape the character with a '\'. So `telegram.sh /tmp/test 1.jpg` should be `telegram.sh /tmp/test\ 1.jpg`

Hopefully this was helpful :-)
